remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Food Channel (Domino's) - WiiLink Guides
description: A temporary guide on how to install Food Channel (Domino's)!